steps:
  # Build the container image with no cache
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'gcr.io/$PROJECT_ID/qglide-backend:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/qglide-backend:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'qglide-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/qglide-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'DATABASE_NAME=qglide_prod,DATABASE_USER=qglide_user,DATABASE_HOST=/cloudsql/qglide-472613:us-central1:qglide-db,DATABASE_PORT=5432,DATABASE_PASSWORD=yyvY^sa:2Xge*#F8,EMAIL_HOST_USER=qglideapp@gmail.com,EMAIL_HOST_PASSWORD=lidtoxqtmntlmjwh,FIREBASE_PROJECT_ID=qglide-firebase,DEBUG=False,SECRET_KEY=N5V@k)+-tSwDlM!n+T^SdXOjsTxirHT+xHEau$5+d7iCsH=Q0I,FIREBASE_CREDENTIALS_PATH=/app/qglide.json'

images:
  - 'gcr.io/$PROJECT_ID/qglide-backend:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY