#!/bin/bash

# Manual deployment instructions for QGlide Backend
# Since gcloud CLI has Python dependency issues, use Google Cloud Console

echo "🚀 Manual Deployment Instructions for QGlide Backend"
echo "=================================================="
echo ""
echo "Since gcloud CLI has Python dependency issues, please use Google Cloud Console:"
echo ""
echo "1. Go to: https://console.cloud.google.com/run"
echo "2. Select project: qglide-472613"
echo "3. Click on 'qglide-backend' service"
echo "4. Click 'EDIT & DEPLOY NEW REVISION'"
echo "5. Update the following:"
echo ""
echo "   Container Image URL: gcr.io/qglide-472613/qglide-backend:latest"
echo ""
echo "   Environment Variables:"
echo "   - ENVIRONMENT=production"
echo "   - DATABASE_NAME=qglide_prod"
echo "   - DATABASE_USER=qglide_user"
echo "   - DATABASE_PASSWORD=QGlide2024!Secure"
echo "   - DATABASE_HOST=136.115.154.205"
echo "   - DATABASE_PORT=5432"
echo "   - SECRET_KEY=django-insecure-temp-key-please-change"
echo "   - MAILERSEND_API_KEY="
echo "   - MAILERSEND_DOMAIN="
echo "   - BREVOR_API_KEY="
echo "   - EMAIL_HOST_USER=your-email@gmail.com"
echo "   - EMAIL_HOST_PASSWORD=your-gmail-app-password"
echo "   - DEFAULT_FROM_EMAIL=noreply@qglide.com"
echo "   - FIREBASE_CREDENTIALS_PATH=/app/firebase-service-account.json"
echo "   - FIREBASE_PROJECT_ID=qglide-firebase"
echo ""
echo "   Cloud SQL Connections:"
echo "   - qglide-472613:us-central1:qglide-db"
echo ""
echo "6. Click 'DEPLOY'"
echo ""
echo "✅ After deployment, your service will be available at:"
echo "   https://qglide-backend-897216835153.us-central1.run.app"
echo ""
echo "📊 Test the Gmail SMTP OTP functionality:"
echo "   1. Go to: https://qglide-backend-897216835153.us-central1.run.app/"
echo "   2. Use Swagger UI to test the registration endpoint"
echo "   3. Check your email for the OTP"
echo ""
echo "🔧 To fix gcloud CLI permanently:"
echo "   1. Install gcloud CLI using Homebrew: brew install google-cloud-sdk"
echo "   2. Or reinstall from: https://cloud.google.com/sdk/docs/install"
echo ""
